language: php

sudo: false

env:
  global:
    - RUN_PHPCS="no"
    - COMPOSER_FLAGS=""

matrix:
  fast_finish: true
  include:
    - php: 5.3
    - php: 5.3
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env: RUN_PHPCS="yes"
    - php: 7.0
    - php: 7.1
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # Until the next major stable image update
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer update $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit
  - if [ "$RUN_PHPCS" == "yes" ]; then vendor/bin/phpcs -p --report=full --extensions=php --standard=.travis/phpcs/Joomla/ruleset.xml src/; fi;
